# Generated by Django 2.2.5 on 2019-10-07 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20191007_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='user',
            new_name='user2',
        ),
    ]
